//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Roxane Morin")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("0.1")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("0.1+1258cc4af335614daf6f5cb3f61bfafaeb22ce64")]
[assembly: System.Reflection.AssemblyProductAttribute("Crisps\' Overlay Package Cloner")]
[assembly: System.Reflection.AssemblyTitleAttribute("CrispsOverlayPackageCloner")]
[assembly: System.Reflection.AssemblyVersionAttribute("0.1")]
[assembly: System.Runtime.Versioning.TargetPlatformAttribute("Windows7.0")]
[assembly: System.Runtime.Versioning.SupportedOSPlatformAttribute("Windows7.0")]

// Generated by the MSBuild WriteCodeFragment class.

