//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Roxane Morin")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Release")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("0.1")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("0.1+e9a0f6ea6f6beab736ce076d5c955e7c27acedd3")]
[assembly: System.Reflection.AssemblyProductAttribute("Crisps\' Overlay Package Cloner")]
[assembly: System.Reflection.AssemblyTitleAttribute("CrispsOverlayPackageCloner")]
[assembly: System.Reflection.AssemblyVersionAttribute("0.1")]
[assembly: System.Runtime.Versioning.TargetPlatformAttribute("Windows10.0.17763.0")]
[assembly: System.Runtime.Versioning.SupportedOSPlatformAttribute("Windows10.0.17763.0")]

// Generated by the MSBuild WriteCodeFragment class.

